<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\BudgetItem $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2>
            <?= $model->name ?>        </h2>
    </div>

    <div class="panel-body">

        <div class="budget-item-form">

            <?php $form = ActiveForm::begin([
                    'id' => 'BudgetItem',
                    'layout' => 'horizontal',
                    'enableClientValidation' => true,
                    'errorSummaryCssClass' => 'error-summary alert alert-error'
                ]
            );
            ?>

            <div class="">
                <?php $this->beginBlock('main'); ?>


                <p></p>
                <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                $form->field($model, 'parent_id')->dropDownList(
                    (new \app\models\BudgetItem())->getTabList(),
                    ['prompt' => Yii::t('app', 'Select')]
                ); ?>
                <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                $form->field($model, 'currency_id')->dropDownList(
                    app\models\Currency::getActiveCurrency(),
                    ['prompt' => Yii::t('app', 'Select')]
                ); ?>
                <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                $form->field($model, 'type_budget_item_id')->dropDownList(
                    \yii\helpers\ArrayHelper::map(app\models\TypeBudgetItem::find()->all(), 'id', 'type'),
                    ['prompt' => Yii::t('app', 'Select')]
                ); ?>
                <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'ammount')->textInput() ?>
                <div class="form-group">
                    <label class="control-label col-sm-3" for="budgetitem-date">Планируемая дата</label>
                    <div class="col-sm-6">
                        <?=kartik\date\DatePicker::widget([
                            'model' => $model,
                            'attribute' => 'date',
                            'pluginOptions' => ['format' => 'dd.mm.yyyy', 'class' => 'col-sm-6'],
                        ])?>
                    </div>
                </div>


                <?php $this->endBlock(); ?>

                <?=
                Tabs::widget(
                    [
                        'encodeLabels' => false,
                        'items' => [ [
                            'label'   => Yii::t('app', 'Budget Item'),
                            'content' => $this->blocks['main'],
                            'active'  => true,
                        ], ]
                    ]
                );
                ?>
                <hr/>
                <?php echo $form->errorSummary($model); ?>
                <?= Html::submitButton(
                    '<span class="glyphicon glyphicon-check"></span> ' .
                    ($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')),
                    [
                        'id' => 'save-' . $model->formName(),
                        'class' => 'btn btn-success'
                    ]
                );
                ?>

                <?php ActiveForm::end(); ?>

            </div>

        </div>

    </div>

</div>
