<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\BudgetItem $model
 */
$this->title = 'Budget Item ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Budget Items'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'View');
?>
<div class="giiant-crud budget-item-view">

    <!-- menu buttons -->
    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('app', 'Edit'), ['update', 'id' => $model->id],['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <p class="pull-right">
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'List BudgetItems'), ['index'], ['class'=>'btn btn-default']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>
                <?= $model->name ?>            </h2>
        </div>

        <div class="panel-body">



            <?php $this->beginBlock('app\models\BudgetItem'); ?>

            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
//                    'id',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
                    [
                        'format' => 'html',
                        'attribute' => 'parent_id',
                        'value' => ($model->getParent()->one() ? Html::a($model->getParent()->one()->name, ['budget-item/view', 'id' => $model->getParent()->one()->id,]) : '<span class="label label-warning">?</span>'),
                    ],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
                    [
                        'format' => 'html',
                        'attribute' => 'currency_id',
                        'value' => ($model->getCurrency()->one()) ? $model->getCurrency()->one()->name : '<span class="label label-warning">?</span>',
                    ],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
                    [
                        'format' => 'html',
                        'attribute' => 'type_budget_item_id',
                        'value' => Html::tag('span', \yii\helpers\ArrayHelper::getValue($model::getTypes(), $model->type_budget_item_id), ['class' => 'label label-' . \yii\helpers\ArrayHelper::getValue($model::getTypesCssClass(), $model->type_budget_item_id)]),
//                        'value' => \yii\helpers\ArrayHelper::getValue($model::getTypes(), $model->type_budget_item_id),
                    ],
                    'name',
                    'ammount:currency',
                    'date:date',
//                    'active',
                ],
            ]); ?>

            <hr/>

            <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('app', 'Delete'), ['delete', 'id' => $model->id],
                [
                    'class' => 'btn btn-danger',
                    'data-confirm' => '' . Yii::t('app', 'Are you sure to delete this item?') . '',
                    'data-method' => 'post',
                ]); ?>
            <?php $this->endBlock(); ?>




            <?= Tabs::widget(
                [
                    'id' => 'relation-tabs',
                    'encodeLabels' => false,
                    'items' => [ [
                        'label'   => '<b class=""># '.$model->name.'</b>',
                        'content' => $this->blocks['app\models\BudgetItem'],
                        'active'  => true,
                    ] ]
                ]
            );
            ?>
        </div>
    </div>
</div>
