<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Ammount' => '',
    'Apply Time' => '',
    'Are you sure to delete this item?' => '',
    'Auth Key' => '',
    'Budget' => '',
    'Budget History' => '',
    'Budget ID' => '',
    'Budget Item' => '',
    'Budget Item ID' => '',
    'Budget Items' => '',
    'Budgets' => 'Бюджет',
    'Cancel' => '',
    'Ch Code' => '',
    'Code' => '',
    'Create' => '',
    'Created Date' => '',
    'Currencies' => '',
    'Currency' => '',
    'Currency Cur' => '',
    'Currency ID' => '',
    'Curs' => '',
    'Date' => '',
    'Delete' => '',
    'Edit' => '',
    'Email' => '',
    'Email Confirm Token' => '',
    'First' => '',
    'ID' => '',
    'Last' => '',
    'List All' => '',
    'List BudgetItems' => '',
    'List Budgets' => '',
    'List Currencies' => '',
    'Name' => '',
    'New' => 'Создать',
    'Nom' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Patent ID' => '',
    'Rate' => '',
    'Relations' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Select' => '',
    'Sign' => '',
    'Status' => '',
    'Title' => '',
    'Type' => '',
    'Type Budget Item' => '',
    'Type Budget Item ID' => '',
    'Updated Date' => '',
    'User' => '',
    'User ID' => '',
    'Version' => '',
    'View' => '',
    'Password' => 'Пароль',
    'Remember Me' => 'Запомнить меня',
    'Username' => 'Имя пользователя',
];
