<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Apply Time' => '',
    'Are you sure to delete this item?' => 'Вы действительно хотите удалить этот элемент?',
    'Auth Key' => '',
    'Budget Histories' => '',
    'Budget ID' => 'Бюджет',
    'Budget Item ID' => 'Статья бюджета',
    'Cancel' => 'Отмена',
    'Ch Code' => '',
    'Code' => '',
    'Currencies' => '',
    'Currency Cur' => '',
    'Curs' => '',
    'Email' => '',
    'Email Confirm Token' => '',
    'First' => '',
    'ID' => '',
    'It is recommended you use an upgraded browser to display the {type} control properly.' => '',
    'Last' => '',
    'List All' => '',
    'List BudgetHistories' => '',
    'List Currencies' => '',
    'Nom' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Rate' => '',
    'Relations' => '',
    'Reset' => 'Сбросить',
    'Search' => '',
    'Sign' => '',
    'Status' => '',
    'Type' => '',
    'User ID' => '',
    'Version' => '',
    'Budget History' => '@@@@',
    'Currency' => '@@@@',
    'Patent ID' => '@@@@',
    'Type Budget Item' => '@@@@',
    'Ammount' => 'Сумма',
    'Ammount Limit' => 'Сумма лимита по статье',
    'Budget' => 'Бюджет',
    'Budget Item' => 'Статья бюджета',
    'Budget Items' => 'Статьи бюджета',
    'Budgets' => 'Бюджет',
    'Costs Limit' => 'Лимит расходов',
    'Create' => 'Создать',
    'Created Date' => 'Дата создания',
    'Currency ID' => 'Валюта',
    'Date' => 'Дата',
    'Delete' => 'Удалить',
    'Edit' => 'Редактировать',
    'Income Limit' => 'Ожидаемый уровень доходов',
    'List BudgetItems' => 'Список Статей бюджета',
    'List Budgets' => 'Список Бюджетов',
    'Name' => 'Название',
    'New' => 'Создать',
    'New costs' => 'Зафиксировать трату',
    'New income' => 'Зафиксировать доход',
    'Parent ID' => 'Родительская статья',
    'Password' => 'Пароль',
    'Planned Date' => 'Планируемая Дата',
    'Remember Me' => 'Запомнить меня',
    'Save' => 'Сохранить',
    'Select' => 'Выбрать',
    'Title' => 'Название',
    'Type Budget Item ID' => 'Тип статьи',
    'Updated Date' => 'Дата изменения',
    'User' => '@@@@',
    'Username' => 'Имя пользователя',
    'View' => 'Просмотр',
    'Date form' => 'Период с',
    'Date to' => 'Период по',
    'Report' => 'Отчеты',
    'View report' => 'Сформировать Отчет',
];
